fmralign/fmralign

- fmralign/alignment_methods.py
- fmralign/tests/test_alignment_methods.py
I added/modified tests for projection scheme and class appropriatly.
New tests pass except once that can fail from time to time but this problem is already patched in PR #4
> [MRG] Implemented diagonal estimator to solve Issue #7

- fmralign/alignment_methods.py
- fmralign/version.py
- setup.py
> Make POT an optional dependency

- README.md
correcting some typo, a short help for developer mode installation and updating documentation link
> Readme Release Update

- fmralign/_utils.py
- fmralign/pairwise_alignment.py
- fmralign/template_alignment.py
- fmralign/tests/test_pairwise_alignment.py
- fmralign/tests/test_utils.py
Important for working on timeseries data and useful overall. The algorithmic part will be removed when merged into nilearn.regions
> Reput hierarchical_kmeans in fmralign

- AUTHORS.rst
- fmralign/_utils.py
- fmralign/alignment_methods.py
- fmralign/metrics.py
- fmralign/pairwise_alignment.py
- fmralign/template_alignment.py
- fmralign/tests/test_alignment_methods.py
- fmralign/tests/test_pairwise_alignment.py
- fmralign/tests/test_utils.py
- Fix a bug #45 ignoring the nifti clustering when it was given with n_pieces = 1 in PairwiseAlignment
- Refactored everything related to clustering in _make_parcellation function.
- Add more extensive tests for clustering scenarios
- Improve verbose on clustering, raise warning for parcels >1000 voxels and error when trying to align with optimal transport on parcels >5000
- Docstring improvements
- add Elizabeth as a contributor
> [FIX, ENH, MRG] Improve clustering functions, tests, 

- examples/plot_alignment_methods_benchmark.py
- examples/plot_pairwise_alignment.py
- examples/plot_pairwise_roi_alignment.py
- examples/plot_template_alignment.py
- fmralign/pairwise_alignment.py
- fmralign/template_alignment.py
- fmralign/version.py
This bumps to a min nilearn version of 0.9.0 and updates corresponding imports in the package.
cc @bthirion for feedback !
> [ENH] Bump to nilearn v0.9

- fmralign/_utils.py
- fmralign/alignment_methods.py
> Fixed tests

- .circleci/config.yml
- .github/workflows/testing.yml
- doc/functional_alignment/fmralign_pipeline.rst
- doc/functional_alignment/functional_alignment_intro.rst
- examples/plot_alignment_methods_benchmark.py
- fmralign/_utils.py
- fmralign/alignment_methods.py
- fmralign/fetch_example_data.py
- fmralign/metrics.py
- fmralign/pairwise_alignment.py
- fmralign/template_alignment.py
- fmralign/tests/test_alignment_methods.py
- fmralign/tests/test_metrics.py
- fmralign/tests/test_pairwise_alignment.py
- fmralign/tests/test_template_alignment.py
- fmralign/tests/test_utils.py
- fmralign/tests/utils.py
- pyproject.toml
This ended up focuses on fixing (relates to #62) and reducing the number of warnings in the test suite. I've also added a GHA to run these on push, so any future failures should be obvious !
> [MAINT] Fix tests

- .flake8
- .github/workflows/testing.yml
- examples/plot_alignment_methods_benchmark.py
- examples/plot_alignment_simulated_2D_data.py
- examples/plot_pairwise_alignment.py
- examples/plot_pairwise_roi_alignment.py
- examples/plot_template_alignment.py
- fmralign/_utils.py
- fmralign/alignment_methods.py
- fmralign/fetch_example_data.py
- fmralign/metrics.py
- fmralign/template_alignment.py
- fmralign/tests/test_pairwise_alignment.py
- fmralign/tests/test_utils.py
- fmralign/tests/utils.py
- pyproject.toml
Allow a pretty generous line-length of 95 characters for now
> [FMT] Re-introduce flake8, solve existing fmt errors

- .github/doc-build.yml
Try to build docs with GHA and host on gh-pages branch, rather than build locally and host on fmralign-docs.
> [INFRA] First pass at doc builder GHA

- fmralign/_utils.py
- fmralign/fetch_example_data.py
- fmralign/pairwise_alignment.py
- fmralign/srm.py
- fmralign/template_alignment.py
- fmralign/tests/test_srm.py
- pyproject.toml
Closes #78 
- Bumps min version for Nilearn dependency to 0.10.3
- Updates associated calls for (previously) Nilearn private functions
Tests running green locally ✅
> [INFRA] nilearn updates

- .github/workflows/doc-build.yml
With @pbarbarant, adventuring into the unknown 🚀
> [INFRA] Try doc deployment from jupyter-book

- fmralign/fetch_example_data.py
> [HOTFIX] Fix ibc fetcher

- fmralign/fetch_example_data.py
- fmralign/pairwise_alignment.py
- fmralign/template_alignment.py
> Rename functional_alignment to fmralign

- doc/modules/reference.rst
- fmralign/alignment_methods.py
- fmralign/tests/conftest.py
- fmralign/tests/test_alignment_methods.py
Adds an option to OptimalTransportAlignment to support unbalancing.
> [ENH] Add Unbalanced Wasserstein

- fmralign/tests/test_preprocessing.py
Adds unit test for passing precomputed surface clustering image.
> [TEST] Add surfacic clustering test

- doc/modules/reference.rst
- fmralign/alignment_methods.py
- fmralign/pairwise_alignment.py
- fmralign/template_alignment.py
- fmralign/tests/test_alignment_methods.py
- fmralign/tests/test_pairwise_alignment.py
- fmralign/tests/test_template_alignment.py
> [MAINT] Remove Hungarian permutation alignment

- fmralign/_utils.py
- fmralign/preprocessing.py
- fmralign/sparse_pairwise_alignment.py
- pyproject.toml
Resolves test failures with latest release of nilearn
Extra changes to pyproject.toml introduced when touching file, given new pre-commit rules (pulled to match nilearn's rules).
> [MAINT, FIX] Move nilearn pin

- README.md
- examples/plot_alignment_methods_benchmark.py
- fmralign/alignment_methods.py
- fmralign/pairwise_alignment.py
- fmralign/preprocessing.py
- fmralign/tests/test_alignment_methods.py
- fmralign/tests/test_sparse_template_alignment.py
- pyproject.toml
> [BACKEND] Remove jax and make POT the default OT implementation

- .github/workflows/doc-build.yml
- .github/workflows/testing.yml
- README.md
- doc/Makefile
- doc/index.rst
- doc/sphinxext/gh_substitutions.py
Closes #153 . Old org Parietal-INRIA has been replaced by fmralign
> [MAINT] Fix old parietal-inria links

- fmralign/pairwise_alignment.py
- fmralign/preprocessing.py
- fmralign/sparse_pairwise_alignment.py
- fmralign/sparse_template_alignment.py
- fmralign/srm.py
- fmralign/template_alignment.py
- fmralign/tests/test_preprocessing.py
Closes #152 . Ward parcellation is now the default instead of kmeans
> [ENH] Use ward by default

- examples/plot_alignment_methods_benchmark.py
- examples/plot_alignment_simulated_2D_data.py
- examples/plot_pairwise_alignment.py
- examples/plot_pairwise_roi_alignment.py
- examples/plot_surf_alignment.py
- examples/plot_template_alignment.py
This PR adapts the examples to the new API and by applying minimal modifications as to the originals.
TODO:
> [API] Adapt the examples
